# Generated by Django 6.0 on 2025-12-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('sub', models.CharField(blank=True, max_length=180)),
                ('badge', models.CharField(blank=True, max_length=60)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('wa_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='kuttuktoo', max_length=80)),
                ('subtitle', models.CharField(blank=True, default='видео + тарифтер', max_length=120)),
                ('whatsapp_link', models.URLField(blank=True, default='https://wa.me/996221000953')),
                ('footer_text', models.CharField(blank=True, default='© REKLAM', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='OfferFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='offers.offer')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offers/videos/')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='offers.offer')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
