# Generated by Django 5.2.9 on 2025-12-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='offerfeature',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Пункт тарифа', 'verbose_name_plural': 'Пункты тарифа'},
        ),
        migrations.AlterModelOptions(
            name='offervideo',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Видео тарифа', 'verbose_name_plural': 'Видео тарифов'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='badge',
            field=models.CharField(blank=True, help_text='Например: VIP, Көп алынат, Сунуштайм', max_length=60, verbose_name='Бейдж (лейбл)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='key',
            field=models.SlugField(help_text='Уникальный ключ тарифа, например: econom, standard, invite', max_length=64, unique=True, verbose_name='Ключ (slug)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(blank=True, help_text='Например: "2 000 сом"', max_length=40, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sub',
            field=models.CharField(blank=True, max_length=180, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='wa_text',
            field=models.CharField(blank=True, help_text='Сообщение, которое уйдет в WhatsApp при нажатии «Заказ берүү»', max_length=255, verbose_name='Текст для WhatsApp'),
        ),
        migrations.AlterField(
            model_name='offerfeature',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='offers.offer', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='offerfeature',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='offerfeature',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст пункта'),
        ),
        migrations.AlterField(
            model_name='offervideo',
            name='duration',
            field=models.CharField(blank=True, help_text='Например: "0:56"', max_length=20, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='offervideo',
            name='file',
            field=models.FileField(upload_to='offers/videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='offervideo',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='offers.offer', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='offervideo',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(blank=True, default='kuttuktoo', max_length=80, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© REKLAM', max_length=120, verbose_name='Текст в футере'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subtitle',
            field=models.CharField(blank=True, default='видео + тарифтер', max_length=120, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.URLField(blank=True, default='https://wa.me/996221000953', verbose_name='Ссылка WhatsApp'),
        ),
    ]
