# Generated by Django 5.2.9 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_alter_offer_options_alter_offerfeature_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offervideo",
            old_name="file",
            new_name="desktop_file",
        ),
        migrations.AlterField(
            model_name="offervideo",
            name="desktop_file",
            field=models.FileField(upload_to="offers/videos/desktop/", verbose_name="Видео для ПК"),
        ),
        migrations.AddField(
            model_name="offervideo",
            name="mobile_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="offers/videos/mobile/",
                verbose_name="Видео для мобилки",
            ),
        ),
    ]
