# Generated by Django 5.2.9 on 2026-01-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_rename_file_to_desktop_file_add_mobile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offervideo",
            old_name="desktop_file",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="offervideo",
            name="mobile_file",
        ),
        migrations.AlterField(
            model_name="offervideo",
            name="file",
            field=models.FileField(upload_to="offers/videos/", verbose_name="Видео файл"),
        ),
        migrations.CreateModel(
            name="OfferDeviceVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "desktop_file",
                    models.FileField(upload_to="offers/videos/desktop/", verbose_name="Видео для ПК"),
                ),
                (
                    "mobile_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="offers/videos/mobile/",
                        verbose_name="Видео для мобилки",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text='Например: "0:56"', max_length=20, verbose_name="Длительность"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_videos",
                        to="offers.offer",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео тарифа (по устройствам)",
                "verbose_name_plural": "Видео тарифов (по устройствам)",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
