# Generated by Django 5.2.9 on 2026-01-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_revert_offervideo_add_offerdevicevideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offerdevicevideo",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="offerdevicevideo",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="offer",
            name="device_video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer",
                to="offers.offerdevicevideo",
                verbose_name="Видео (мобилка/ПК)",
            ),
        ),
        migrations.AlterModelOptions(
            name="offerdevicevideo",
            options={
                "ordering": ["id"],
                "verbose_name": "Видео тарифа (по устройствам)",
                "verbose_name_plural": "Видео тарифов (по устройствам)",
            },
        ),
    ]

